"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import {
  Building2,
  Check,
  Eye,
  FileText,
  LayoutTemplate,
  PackageSearch,
  Palette,
  ReceiptText,
  RotateCcw,
} from "lucide-react";
import {
  DEFAULT_PURCHASE_RETURN_PRINT_CUSTOMIZATION,
  getPurchaseReturnPrintCustomization,
  resetPurchaseReturnPrintCustomization,
  setPurchaseReturnPrintCustomization,
  subscribePurchaseReturnPrintCustomization,
  type PurchaseReturnPrintCustomization,
} from "@/lib/print/purchaseReturnPrintCustomization";
import {
  buildPurchaseReturnInvoiceHtml,
  type PurchaseReturnPrintInput,
} from "@/lib/print/buildPurchaseReturnInvoiceHtml";

type ToggleDefinition = {
  key: keyof PurchaseReturnPrintCustomization;
  label: string;
  description: string;
};

type EditorTab = "style" | "business" | "document" | "items";

const BUSINESS_TOGGLES: ToggleDefinition[] = [
  {
    key: "showLogo",
    label: "Logo",
    description: "Show the saved business logo.",
  },
  {
    key: "showShopName",
    label: "Business name",
    description: "Show the shop or company name.",
  },
  {
    key: "showShopAddress",
    label: "Address",
    description: "Show the saved address and location.",
  },
  {
    key: "showShopPhone",
    label: "Phone",
    description: "Show the saved business phone.",
  },
  {
    key: "showShopEmail",
    label: "Email",
    description: "Show the saved business email.",
  },
  {
    key: "showShopGstin",
    label: "GSTIN",
    description: "Show the business GST registration number.",
  },
];

const DOCUMENT_TOGGLES: ToggleDefinition[] = [
  {
    key: "showSupplierName",
    label: "Supplier name",
    description: "Show the supplier or Cash Return label.",
  },
  {
    key: "showSupplierAddress",
    label: "Supplier address",
    description: "Show the supplier address when available.",
  },
  {
    key: "showSupplierPhone",
    label: "Supplier phone",
    description: "Show the supplier phone when available.",
  },
  {
    key: "showSupplierEmail",
    label: "Supplier email",
    description: "Show the supplier email when available.",
  },
  {
    key: "showSupplierGstin",
    label: "Supplier GSTIN",
    description: "Show the supplier GSTIN when available.",
  },
  {
    key: "showEntryNo",
    label: "Entry number",
    description: "Show the internal Purchase Return number.",
  },
  {
    key: "showBillNo",
    label: "Supplier bill number",
    description: "Show the supplier invoice or bill number.",
  },
  {
    key: "showPurchaseDate",
    label: "Return date",
    description: "Show the saved Return date.",
  },
  {
    key: "showEntryTime",
    label: "Entry time",
    description: "Show the saved entry time.",
  },
  {
    key: "showPurchaseType",
    label: "Return type",
    description: "Show Cash or Credit.",
  },
  {
    key: "showTransactionType",
    label: "Transaction type",
    description: "Show the selected transaction type.",
  },
  {
    key: "showDepartment",
    label: "Department",
    description: "Show the optional department reference.",
  },
  {
    key: "showDebitAccount",
    label: "Debit account",
    description: "Show the optional debit-account reference.",
  },
  {
    key: "showNatureOfEntry",
    label: "Nature of entry",
    description: "Show the optional Purchase Return description.",
  },
];

const ITEM_TOGGLES: ToggleDefinition[] = [
  {
    key: "showBarcode",
    label: "Barcode",
    description: "Show barcode below the item name.",
  },
  {
    key: "showBatchNo",
    label: "Batch number",
    description: "Show batch information when available.",
  },
  {
    key: "showExpiryDate",
    label: "Expiry",
    description: "Show item expiry information.",
  },
  {
    key: "showUnit",
    label: "Unit",
    description: "Show unit on A4 and thermal output.",
  },
  {
    key: "showTax",
    label: "Tax",
    description: "Show included-tax value and percentage.",
  },
];

const FOOTER_TOGGLES: ToggleDefinition[] = [
  {
    key: "showAmountInWords",
    label: "Amount in words",
    description: "Write the final amount in words.",
  },
  {
    key: "showTerms",
    label: "Terms / footer note",
    description: "Show the Business Profile invoice footer.",
  },
  {
    key: "showAuthorizedSignatory",
    label: "Authorized signature",
    description: "Show the signature area.",
  },
  {
    key: "showKynflowFooter",
    label: "KYNFLOW footer",
    description: "Show the small Generated by KYNFLOW line.",
  },
];

const tabs: Array<{
  key: EditorTab;
  label: string;
  description: string;
  icon: typeof Palette;
}> = [
  {
    key: "style",
    label: "Style",
    description: "A4 appearance",
    icon: Palette,
  },
  {
    key: "business",
    label: "Business",
    description: "Header visibility",
    icon: Building2,
  },
  {
    key: "document",
    label: "Return",
    description: "Document fields",
    icon: FileText,
  },
  {
    key: "items",
    label: "Items & Footer",
    description: "Rows and totals",
    icon: PackageSearch,
  },
];

const inputClass =
  "w-full rounded-lg border border-slate-200 bg-white px-2.5 py-2 text-xs text-slate-800 outline-none transition placeholder:text-slate-400 focus:border-cyan-400 focus:ring-2 focus:ring-cyan-100";

function ToggleRow({
  definition,
  checked,
  onChange,
}: {
  definition: ToggleDefinition;
  checked: boolean;
  onChange: (checked: boolean) => void;
}) {
  return (
    <button
      type="button"
      onClick={() => onChange(!checked)}
      className={`flex min-h-[50px] items-center justify-between gap-3 rounded-xl border px-3 py-2 text-left transition ${
        checked
          ? "border-slate-300 bg-white shadow-sm"
          : "border-slate-200 bg-slate-100/70"
      } hover:border-cyan-300`}
      aria-pressed={checked}
    >
      <span className="min-w-0">
        <span className="block text-[11px] font-semibold text-slate-800">
          {definition.label}
        </span>
        <span className="mt-0.5 block text-[9px] leading-[14px] text-slate-500">
          {definition.description}
        </span>
      </span>

      <span
        className={`relative inline-flex h-5 w-9 shrink-0 items-center rounded-full transition ${
          checked ? "bg-cyan-500" : "bg-slate-300"
        }`}
      >
        <span
          className={`h-3.5 w-3.5 rounded-full bg-white shadow transition-transform ${
            checked ? "translate-x-[18px]" : "translate-x-[3px]"
          }`}
        />
      </span>
    </button>
  );
}

function ToggleGrid({
  definitions,
  prefs,
  onChange,
}: {
  definitions: ToggleDefinition[];
  prefs: PurchaseReturnPrintCustomization;
  onChange: (
    key: keyof PurchaseReturnPrintCustomization,
    checked: boolean,
  ) => void;
}) {
  return (
    <div className="grid gap-2 sm:grid-cols-2">
      {definitions.map((definition) => (
        <ToggleRow
          key={String(definition.key)}
          definition={definition}
          checked={Boolean(prefs[definition.key])}
          onChange={(checked) => onChange(definition.key, checked)}
        />
      ))}
    </div>
  );
}

function PurchaseReturnTemplatePreview({
  prefs,
}: {
  prefs: PurchaseReturnPrintCustomization;
}) {
  const previewHtml = useMemo(() => {
    const input: PurchaseReturnPrintInput = {
      shop: {
        name: "KYNSTACK TRADERS",
        logoUrl: null,
        addressLine1: "Business Street",
        addressLine2: "Market Junction",
        city: "Kochi",
        state: "Kerala",
        pincode: "682001",
        mobile: "+91 98765 43210",
        email: "billing@example.com",
        gstin: "32ABCDE1234F1Z5",
        footerNote: "Please verify quantities and values before acceptance.",
        authorizedSignatory: "Authorized Signatory",
      },
      options: prefs,
      bill: {
        entryNo: "PR-000042",
        billNo: "RET-2841",
        date: "2026-08-05",
        time: "2026-08-05T14:30:00",
        supplierName: "Reliable Supplies Pvt. Ltd.",
        supplierAddress: "Market Road, Kochi, Kerala - 682018",
        supplierPhone: "+91 98470 12345",
        supplierEmail: "accounts@reliablesupplies.in",
        supplierGstin: "32ABCDE1234F1Z5",
        department: "Main Store",
        debitAccount: "Purchase Return Account",
        natureOfEntry: "Supplier return",
        purchaseType: "Credit",
        transactionType: "Purchase Return",
      },
      items: [
        {
          lineNo: 1,
          name: "Premium Product",
          barcode: "8901234567890",
          batchNo: "BT-124",
          expiryDate: "2027-08-31",
          qty: 2,
          unit: "Nos",
          rate: 625,
          taxPercent: 5,
          amount: 1250,
        },
        {
          lineNo: 2,
          name: "Standard Item",
          barcode: "8901234567807",
          batchNo: "BT-211",
          expiryDate: "2027-12-31",
          qty: 4,
          unit: "Nos",
          rate: 215,
          taxPercent: 5,
          amount: 860,
        },
        {
          lineNo: 3,
          name: "Service Material",
          barcode: "8901234567814",
          batchNo: "BT-309",
          expiryDate: "2028-03-31",
          qty: 2,
          unit: "Box",
          rate: 710,
          taxPercent: 12,
          amount: 1420,
        },
        {
          lineNo: 4,
          name: "Packaging Material",
          barcode: "8901234567821",
          batchNo: "BT-410",
          expiryDate: "2028-06-30",
          qty: 5,
          unit: "Pack",
          rate: 200,
          taxPercent: 5,
          amount: 1000,
        },
      ],
      subTotal: 4530,
      discount: 120,
      grandTotal: 4410,
    };

    const html = buildPurchaseReturnInvoiceHtml(input);
    const fitStyles = [
      '<style id="kynflow-template-preview-fit">',
      "html, body { width: 210mm !important; min-height: 297mm !important; overflow: hidden !important; background: #ffffff !important; }",
      "body { transform-origin: top left !important; }",
      ".modern-invoice, .classic-bill { margin: 0 auto !important; box-shadow: none !important; }",
      "</style>",
    ].join("");

    return html.replace("</head>", `${fitStyles}</head>`);
  }, [prefs]);

  const previewFrameRef = useRef<HTMLIFrameElement>(null);

  useEffect(() => {
    const frame = previewFrameRef.current;
    if (!frame) return;

    const doc = frame.contentDocument;
    if (!doc) return;

    let cancelled = false;
    let animationFrame = 0;
    let retryTimer = 0;
    let resizeObserver: ResizeObserver | null = null;

    const fitPage = () => {
      if (cancelled || !doc.body) return;

      const viewportWidth = frame.clientWidth;
      if (viewportWidth <= 0) return;

      const pageWidthPx = (210 * 96) / 25.4;
      const scale = Math.min(1, viewportWidth / pageWidthPx);

      doc.body.style.width = `${pageWidthPx}px`;
      doc.body.style.transformOrigin = "top left";
      doc.body.style.transform = `scale(${scale})`;
    };

    doc.open();
    doc.write(previewHtml);
    doc.close();

    animationFrame = window.requestAnimationFrame(fitPage);
    retryTimer = window.setTimeout(fitPage, 160);

    if (typeof ResizeObserver !== "undefined") {
      resizeObserver = new ResizeObserver(fitPage);
      resizeObserver.observe(frame);
    }

    return () => {
      cancelled = true;
      window.cancelAnimationFrame(animationFrame);
      window.clearTimeout(retryTimer);
      resizeObserver?.disconnect();
    };
  }, [previewHtml]);

  const isModern = prefs.a4Style === "modern";

  return (
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
      <div className="flex items-center justify-between gap-3 border-b border-slate-200 px-3 py-2.5">
        <div className="flex min-w-0 items-center gap-2">
          <Eye className="h-4 w-4 shrink-0 text-cyan-600" />
          <div className="min-w-0">
            <h4 className="text-xs font-semibold text-slate-800">
              Exact print preview
            </h4>
            <p className="truncate text-[9px] text-slate-500">
              Uses the same renderer family as the final A4 Purchase Return.
            </p>
          </div>
        </div>

        <span className="rounded-full border border-slate-300 bg-white px-2 py-1 text-[8px] font-bold uppercase tracking-[0.12em] text-slate-600">
          {isModern ? "Modern A4" : "Classic A4"}
        </span>
      </div>

      <div className="bg-slate-100 p-3">
        <div className="mx-auto w-full max-w-[430px] overflow-hidden rounded-xl border border-slate-300 bg-white shadow-lg">
          <iframe
            ref={previewFrameRef}
            title={`${isModern ? "Modern" : "Classic"} Purchase Return template preview`}
            src="about:blank"
            className="block aspect-[210/297] w-full border-0 bg-white"
          />
        </div>

        <p className="mt-2 text-center text-[9px] font-medium text-slate-500">
          Sample values only. Layout, spacing, colours and visible fields match
          the real print renderer.
        </p>
      </div>
    </section>
  );
}

export default function PurchaseReturnPrintCustomizationPanel() {
  const [activeTab, setActiveTab] = useState<EditorTab>("style");
  const [prefs, setPrefs] = useState<PurchaseReturnPrintCustomization>(
    DEFAULT_PURCHASE_RETURN_PRINT_CUSTOMIZATION,
  );
  const [headingDraft, setHeadingDraft] = useState(
    DEFAULT_PURCHASE_RETURN_PRINT_CUSTOMIZATION.headingColor,
  );
  const [saved, setSaved] = useState(false);

  useEffect(() => {
    const current = getPurchaseReturnPrintCustomization();
    setPrefs(current);
    setHeadingDraft(current.headingColor);

    return subscribePurchaseReturnPrintCustomization((next) => {
      setPrefs(next);
      setHeadingDraft(next.headingColor);
    });
  }, []);

  function showSaved() {
    setSaved(true);
    window.setTimeout(() => setSaved(false), 1300);
  }

  function updatePreference(
    key: keyof PurchaseReturnPrintCustomization,
    value: string | boolean,
  ) {
    const next = setPurchaseReturnPrintCustomization({
      [key]: value,
    } as Partial<PurchaseReturnPrintCustomization>);
    setPrefs(next);
    showSaved();
  }

  function resetLayout() {
    const next = resetPurchaseReturnPrintCustomization();
    setPrefs(next);
    setHeadingDraft(next.headingColor);
    showSaved();
  }

  return (
    <div className="space-y-3">
      <section className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm sm:flex-row sm:items-center sm:justify-between">
        <div className="flex min-w-0 items-center gap-3">
          <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-slate-900 text-cyan-300">
            <LayoutTemplate className="h-4 w-4" />
          </span>
          <div className="min-w-0">
            <h3 className="text-sm font-semibold text-slate-900">
              Purchase Return template
            </h3>
            <p className="mt-0.5 text-[10px] text-slate-500">
              Changes save automatically and affect A4 and thermal output.
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          {saved && (
            <span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2 py-1 text-[9px] font-semibold text-emerald-600">
              <Check className="h-3 w-3" />
              Saved
            </span>
          )}
          <button
            type="button"
            onClick={resetLayout}
            className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-2.5 py-1.5 text-[10px] font-semibold text-slate-600 transition hover:border-rose-200 hover:bg-rose-50 hover:text-rose-600"
          >
            <RotateCcw className="h-3 w-3" />
            Reset
          </button>
        </div>
      </section>

      <div className="grid grid-cols-2 gap-1 rounded-xl border border-slate-200 bg-slate-100 p-1 sm:grid-cols-4">
        {tabs.map((tab) => {
          const Icon = tab.icon;
          const active = activeTab === tab.key;

          return (
            <button
              key={tab.key}
              type="button"
              onClick={() => setActiveTab(tab.key)}
              className={`flex min-w-0 items-center gap-2 rounded-lg px-2.5 py-2 text-left transition ${
                active
                  ? "bg-white text-slate-900 shadow-sm"
                  : "text-slate-500 hover:bg-white/60 hover:text-slate-800"
              }`}
            >
              <Icon
                className={`h-3.5 w-3.5 shrink-0 ${
                  active ? "text-cyan-600" : "text-slate-400"
                }`}
              />
              <span className="min-w-0">
                <span className="block truncate text-[10px] font-semibold">
                  {tab.label}
                </span>
                <span className="hidden truncate text-[8px] text-slate-400 sm:block">
                  {tab.description}
                </span>
              </span>
            </button>
          );
        })}
      </div>

      {activeTab === "style" && (
        <section className="rounded-2xl border border-slate-200 bg-white p-3 shadow-sm">
          <div className="mb-3 flex items-center gap-2">
            <Palette className="h-4 w-4 text-cyan-600" />
            <div>
              <h4 className="text-xs font-semibold text-slate-800">
                A4 design
              </h4>
              <p className="text-[9px] text-slate-500">
                Thermal stays monochrome and printer-safe.
              </p>
            </div>
          </div>

          <div className="grid gap-3 sm:grid-cols-2">
            <div>
              <label className="mb-1.5 block text-[10px] font-semibold uppercase tracking-[0.1em] text-slate-500">
                A4 style
              </label>
              <div className="grid grid-cols-2 rounded-lg border border-slate-200 bg-slate-100 p-1">
                {(["classic", "modern"] as const).map((style) => (
                  <button
                    key={style}
                    type="button"
                    onClick={() => updatePreference("a4Style", style)}
                    className={`inline-flex items-center justify-center gap-1.5 rounded-md px-2 py-2 text-[10px] font-semibold capitalize transition ${
                      prefs.a4Style === style
                        ? "bg-white text-slate-900 shadow-sm"
                        : "text-slate-500 hover:text-slate-800"
                    }`}
                  >
                    {prefs.a4Style === style && <Check className="h-3 w-3" />}
                    {style}
                  </button>
                ))}
              </div>
            </div>

            <div>
              <label className="mb-1.5 block text-[10px] font-semibold uppercase tracking-[0.1em] text-slate-500">
                Heading colour
              </label>
              <div className="flex gap-2">
                <input
                  type="color"
                  value={prefs.headingColor}
                  onChange={(event) =>
                    updatePreference("headingColor", event.target.value)
                  }
                  className="h-9 w-12 cursor-pointer rounded-lg border border-slate-200 bg-white p-1"
                  aria-label="Purchase Return heading colour"
                />
                <input
                  value={headingDraft}
                  onChange={(event) => setHeadingDraft(event.target.value)}
                  onBlur={() => {
                    const value = headingDraft.trim();
                    if (/^#[0-9a-fA-F]{6}$/.test(value)) {
                      updatePreference("headingColor", value);
                    } else {
                      setHeadingDraft(prefs.headingColor);
                    }
                  }}
                  onKeyDown={(event) => {
                    if (event.key === "Enter") event.currentTarget.blur();
                  }}
                  className={`${inputClass} font-mono uppercase`}
                  maxLength={7}
                />
              </div>
            </div>

            <div className="sm:col-span-2">
              <label className="mb-1.5 block text-[10px] font-semibold uppercase tracking-[0.1em] text-slate-500">
                Document title
              </label>
              <input
                value={prefs.documentTitle}
                onChange={(event) =>
                  updatePreference("documentTitle", event.target.value)
                }
                className={inputClass}
                placeholder="Purchase Return"
              />
            </div>
          </div>
        </section>
      )}

      {activeTab === "business" && (
        <section className="rounded-2xl border border-slate-200 bg-white p-3 shadow-sm">
          <div className="mb-3 flex items-center gap-2">
            <Building2 className="h-4 w-4 text-cyan-600" />
            <div>
              <h4 className="text-xs font-semibold text-slate-800">
                Business header visibility
              </h4>
              <p className="text-[9px] text-slate-500">
                Actual values come from the shared Business Profile.
              </p>
            </div>
          </div>
          <ToggleGrid
            definitions={BUSINESS_TOGGLES}
            prefs={prefs}
            onChange={updatePreference}
          />
        </section>
      )}

      {activeTab === "document" && (
        <section className="rounded-2xl border border-slate-200 bg-white p-3 shadow-sm">
          <div className="mb-3 flex items-center gap-2">
            <FileText className="h-4 w-4 text-cyan-600" />
            <div>
              <h4 className="text-xs font-semibold text-slate-800">
                Purchase Return document details
              </h4>
              <p className="text-[9px] text-slate-500">
                Blank optional values are still omitted automatically.
              </p>
            </div>
          </div>
          <ToggleGrid
            definitions={DOCUMENT_TOGGLES}
            prefs={prefs}
            onChange={updatePreference}
          />
        </section>
      )}

      {activeTab === "items" && (
        <div className="grid gap-3 lg:grid-cols-2">
          <section className="rounded-2xl border border-slate-200 bg-white p-3 shadow-sm">
            <div className="mb-3 flex items-center gap-2">
              <PackageSearch className="h-4 w-4 text-cyan-600" />
              <div>
                <h4 className="text-xs font-semibold text-slate-800">
                  Item details
                </h4>
                <p className="text-[9px] text-slate-500">
                  Optional item metadata and columns.
                </p>
              </div>
            </div>
            <ToggleGrid
              definitions={ITEM_TOGGLES}
              prefs={prefs}
              onChange={updatePreference}
            />
          </section>

          <section className="rounded-2xl border border-slate-200 bg-white p-3 shadow-sm">
            <div className="mb-3 flex items-center gap-2">
              <ReceiptText className="h-4 w-4 text-cyan-600" />
              <div>
                <h4 className="text-xs font-semibold text-slate-800">
                  Totals and footer
                </h4>
                <p className="text-[9px] text-slate-500">
                  Closing information below the item table.
                </p>
              </div>
            </div>
            <ToggleGrid
              definitions={FOOTER_TOGGLES}
              prefs={prefs}
              onChange={updatePreference}
            />
          </section>
        </div>
      )}
      <PurchaseReturnTemplatePreview prefs={prefs} />
    </div>
  );
}
