"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import {
  Building2,
  Check,
  Eye,
  FileText,
  LayoutTemplate,
  PackageSearch,
  Palette,
  RotateCcw,
} from "lucide-react";
import { buildInvoiceHtml } from "@/lib/print/buildInvoiceHtml";
import { buildThermalReceiptHtml } from "@/lib/print/buildThermalReceiptHtml";
import {
  DEFAULT_QUOTATION_PRINT_CUSTOMIZATION,
  getQuotationPrintCustomization,
  resetQuotationPrintCustomization,
  setQuotationPrintCustomization,
  subscribeQuotationPrintCustomization,
  type QuotationPrintCustomization,
} from "@/lib/print/quotationPrintCustomization";
import type { QuotationPrintFormat } from "@/lib/print/quotationPrintSettings";

type Props = {
  format: QuotationPrintFormat;
  onFormatChange: (format: QuotationPrintFormat) => void;
};

type EditorTab = "style" | "business" | "quotation" | "items";

type ToggleDefinition = {
  key: keyof QuotationPrintCustomization;
  label: string;
  description: string;
};

const BUSINESS_TOGGLES: ToggleDefinition[] = [
  {
    key: "showLogo",
    label: "Logo",
    description: "Show the logo saved in the shared Business Profile.",
  },
  {
    key: "showShopName",
    label: "Business name",
    description: "Show the saved shop or company name.",
  },
  {
    key: "showShopAddress",
    label: "Address",
    description: "Show the saved business address.",
  },
  {
    key: "showShopPhone",
    label: "Phone",
    description: "Show the business phone number.",
  },
  {
    key: "showShopEmail",
    label: "Email",
    description: "Show the business email address.",
  },
  {
    key: "showShopGstin",
    label: "GSTIN",
    description: "Show the GSTIN from Business Profile.",
  },
];

const QUOTATION_TOGGLES: ToggleDefinition[] = [
  {
    key: "showEntryNo",
    label: "Entry number",
    description: "Show the internal quotation entry reference.",
  },
  {
    key: "showBillNo",
    label: "Quotation number",
    description: "Show the customer-facing quotation number.",
  },
  {
    key: "showSaleDate",
    label: "Quotation date",
    description: "Show the quotation date.",
  },
  {
    key: "showEntryTime",
    label: "Entry time",
    description: "Show the saved quotation entry time.",
  },
  {
    key: "showDepartment",
    label: "Department",
    description: "Show the selected department when available.",
  },
  {
    key: "showCustomerName",
    label: "Customer name",
    description: "Show the customer name.",
  },
  {
    key: "showCustomerAddress",
    label: "Customer address",
    description: "Show the customer address when available.",
  },
  {
    key: "showCustomerPhone",
    label: "Customer phone",
    description: "Show the customer phone when available.",
  },
  {
    key: "showCustomerGstin",
    label: "Customer GSTIN",
    description: "Show the customer GSTIN when available.",
  },
];

const ITEM_TOGGLES: ToggleDefinition[] = [
  {
    key: "showBarcode",
    label: "Barcode",
    description: "Show item barcode details when available.",
  },
  {
    key: "showBatchNo",
    label: "Batch",
    description: "Show batch number details when available.",
  },
  {
    key: "showExpiryDate",
    label: "Expiry",
    description: "Show expiry details when available.",
  },
  {
    key: "showUnit",
    label: "Unit",
    description: "Show the quoted unit beside quantity.",
  },
  {
    key: "showTax",
    label: "Tax",
    description: "Show item tax information.",
  },
  {
    key: "showMrp",
    label: "MRP",
    description: "Show item MRP when available.",
  },
  {
    key: "showAmountInWords",
    label: "Amount in words",
    description: "Show the quotation total in words.",
  },
  {
    key: "showAuthorizedSignatory",
    label: "Authorized signatory",
    description: "Show the saved signatory at the bottom.",
  },
  {
    key: "showKynflowFooter",
    label: "KYNFLOW footer",
    description: "Show the Generated by KYNFLOW footer line.",
  },
];

const TABS: Array<{
  key: EditorTab;
  label: string;
  icon: typeof Palette;
}> = [
  { key: "style", label: "Style", icon: Palette },
  { key: "business", label: "Business", icon: Building2 },
  { key: "quotation", label: "Quotation", icon: FileText },
  { key: "items", label: "Items & Footer", icon: PackageSearch },
];

const inputClass =
  "h-9 w-full rounded-lg border border-slate-200 bg-white px-2.5 text-xs text-slate-800 outline-none transition focus:border-cyan-400/60 focus:ring-2 focus:ring-cyan-400/10";

function relabelQuotationHtml(html: string): string {
  return html
    .replaceAll("Bill No.", "Quotation No.")
    .replaceAll("<span>Bill</span>", "<span>Quotation</span>")
    .replaceAll("Original customer copy", "Quotation copy");
}

function ToggleRow({
  definition,
  checked,
  onChange,
}: {
  definition: ToggleDefinition;
  checked: boolean;
  onChange: (checked: boolean) => void;
}) {
  return (
    <button
      type="button"
      onClick={() => onChange(!checked)}
      aria-pressed={checked}
      className={`flex min-h-[58px] w-full items-center justify-between gap-3 rounded-xl border px-3 py-2 text-left transition ${
        checked
          ? "border-slate-300 bg-white shadow-sm"
          : "border-slate-200 bg-slate-100/70"
      } hover:border-cyan-300`}
    >
      <span className="min-w-0">
        <span className="block text-xs font-semibold text-slate-800">
          {definition.label}
        </span>
        <span className="mt-0.5 block text-[10px] leading-4 text-slate-500">
          {definition.description}
        </span>
      </span>
      <span
        className={`relative inline-flex h-5 w-9 shrink-0 items-center rounded-full transition ${
          checked ? "bg-cyan-500" : "bg-slate-300"
        }`}
      >
        <span
          className={`h-3.5 w-3.5 rounded-full bg-white shadow transition-transform ${
            checked ? "translate-x-[18px]" : "translate-x-[3px]"
          }`}
        />
      </span>
    </button>
  );
}

function ToggleGrid({
  definitions,
  prefs,
  onChange,
}: {
  definitions: ToggleDefinition[];
  prefs: QuotationPrintCustomization;
  onChange: (key: keyof QuotationPrintCustomization, value: boolean) => void;
}) {
  return (
    <div className="grid gap-2 sm:grid-cols-2">
      {definitions.map((definition) => (
        <ToggleRow
          key={String(definition.key)}
          definition={definition}
          checked={Boolean(prefs[definition.key])}
          onChange={(checked) => onChange(definition.key, checked)}
        />
      ))}
    </div>
  );
}

function QuotationTemplatePreview({
  prefs,
  format,
  onFormatChange,
}: {
  prefs: QuotationPrintCustomization;
  format: QuotationPrintFormat;
  onFormatChange: (format: QuotationPrintFormat) => void;
}) {
  const previewHtml = useMemo(() => {
    const options: QuotationPrintCustomization = {
      ...prefs,
      a4Style:
        format === "modern"
          ? "modern"
          : format === "classic"
            ? "classic"
            : prefs.a4Style,
      documentTitle: "Quotation",
      showSaleType: false,
      showTransactionType: false,
      showDebitAccount: false,
      showNatureOfEntry: false,
      showOffers: false,
      showOfferSavings: false,
    };

    const shop = {
      name: "KYNSTACK TRADERS",
      logoUrl: null,
      addressLine1: "Business Street",
      addressLine2: "Market Junction",
      city: "Kochi",
      state: "Kerala",
      pincode: "682001",
      mobile: "+91 98765 43210",
      email: "billing@example.com",
      gstin: "32ABCDE1234F1Z5",
      footerNote: "Thank you for considering our quotation.",
      authorizedSignatory: "Authorized Signatory",
    };

    const items = [
      {
        lineNo: 1,
        name: "Premium Product",
        barcode: "8901001000012",
        batchNo: "B-2408",
        expiryDate: "2027-08-31",
        qty: 2,
        unit: "NOS",
        rate: 650,
        taxPercent: "P5",
        mrp: 699,
        salePrice: 650,
        offerName: null,
        offerType: null,
        offerDiscountAmount: 0,
        amount: 1365,
      },
      {
        lineNo: 2,
        name: "Standard Product",
        barcode: "8901001000029",
        batchNo: "",
        expiryDate: null,
        qty: 3,
        unit: "NOS",
        rate: 420,
        taxPercent: "NT",
        mrp: 450,
        salePrice: 420,
        offerName: null,
        offerType: null,
        offerDiscountAmount: 0,
        amount: 1260,
      },
    ];

    const subTotal = 2625;
    const discount = 125;
    const grandTotal = 2500;
    const totalQty = 5;

    const html =
      format === "thermal"
        ? buildThermalReceiptHtml({
            shop,
            options,
            billNo: "QT-00128",
            entryNo: "QE-00128",
            date: "2026-08-08",
            time: "2026-08-08T13:30:00",
            department: "Main Store",
            customerName: "Sample Customer",
            customerPhone: "+91 98470 12345",
            customerGstin: "32ABCDE1234F1Z5",
            customerAddress: "Market Road, Kochi, Kerala - 682018",
            items: items.map((item) => ({
              ...item,
              total: item.amount,
              offerLabel: null,
              offerSavings: 0,
            })),
            totalQty,
            subTotal,
            offerSavings: 0,
            offerSummary: [],
            discount,
            grandTotal,
            notes: [
              "Valid for 15 days.",
              "Prices are subject to the stated terms.",
            ],
          })
        : buildInvoiceHtml({
            shop,
            options,
            document: {
              title: "QUOTATION",
              entryNo: "QE-00128",
              billNo: "QT-00128",
              date: "2026-08-08",
              time: "2026-08-08T13:30:00",
              department: "Main Store",
              natureOfEntry: null,
            },
            party: {
              label: "Customer",
              name: "Sample Customer",
              address: "Market Road, Kochi, Kerala - 682018",
              mobile: "+91 98470 12345",
              gstin: "32ABCDE1234F1Z5",
            },
            items,
            subTotal,
            discount,
            offerSavings: 0,
            offerSummary: [],
            grandTotal,
            notes: "Valid for 15 days. Prices are subject to the stated terms.",
          });

    const fitStyles =
      format === "thermal"
        ? [
            '<style id="kynflow-quotation-template-preview-fit">',
            "html, body { width: 80mm !important; margin: 0 !important; overflow: hidden !important; background: #ffffff !important; }",
            "body { transform-origin: top left !important; }",
            ".thermal-receipt, .receipt { margin: 0 auto !important; box-shadow: none !important; }",
            "</style>",
          ].join("")
        : [
            '<style id="kynflow-quotation-template-preview-fit">',
            "html, body { width: 210mm !important; min-height: 297mm !important; margin: 0 !important; overflow: hidden !important; background: #ffffff !important; }",
            "body { transform-origin: top left !important; }",
            ".invoice, .classic-bill, .modern-invoice { margin: 0 auto !important; box-shadow: none !important; }",
            "</style>",
          ].join("");

    return relabelQuotationHtml(html).replace("</head>", `${fitStyles}</head>`);
  }, [format, prefs]);

  const frameRef = useRef<HTMLIFrameElement>(null);

  useEffect(() => {
    const frame = frameRef.current;
    if (!frame) return;

    const doc = frame.contentDocument;
    if (!doc) return;

    let cancelled = false;
    let animationFrame = 0;
    let retryTimer = 0;
    let resizeObserver: ResizeObserver | null = null;

    const fitPage = () => {
      if (cancelled || !doc.body || !doc.documentElement) return;

      const viewportWidth = frame.clientWidth;
      if (viewportWidth <= 0) return;

      const pageWidthMm = format === "thermal" ? 80 : 210;
      const pageHeightMm = format === "thermal" ? null : 297;
      const pageWidthPx = (pageWidthMm * 96) / 25.4;
      const scale = Math.min(1, viewportWidth / pageWidthPx);

      doc.documentElement.style.width = `${pageWidthPx}px`;
      doc.documentElement.style.overflow = "hidden";
      doc.body.style.width = `${pageWidthPx}px`;
      doc.body.style.transformOrigin = "top left";
      doc.body.style.transform = `scale(${scale})`;
      doc.body.style.overflow = "hidden";

      if (pageHeightMm) {
        const pageHeightPx = (pageHeightMm * 96) / 25.4;
        doc.documentElement.style.height = `${pageHeightPx}px`;
        doc.body.style.minHeight = `${pageHeightPx}px`;
        frame.style.height = `${Math.ceil(pageHeightPx * scale)}px`;
      } else {
        doc.documentElement.style.height = "auto";
        doc.body.style.minHeight = "0";
        const contentHeight = Math.max(
          doc.body.scrollHeight,
          doc.documentElement.scrollHeight,
        );
        frame.style.height = `${Math.max(
          220,
          Math.ceil(contentHeight * scale),
        )}px`;
      }
    };

    doc.open();
    doc.write(previewHtml);
    doc.close();

    animationFrame = window.requestAnimationFrame(fitPage);
    retryTimer = window.setTimeout(fitPage, 180);

    if (typeof ResizeObserver !== "undefined") {
      resizeObserver = new ResizeObserver(fitPage);
      resizeObserver.observe(frame);
    }

    window.addEventListener("resize", fitPage);

    return () => {
      cancelled = true;
      window.cancelAnimationFrame(animationFrame);
      window.clearTimeout(retryTimer);
      resizeObserver?.disconnect();
      window.removeEventListener("resize", fitPage);
    };
  }, [format, previewHtml]);

  const label =
    format === "thermal"
      ? "80mm Thermal"
      : format === "modern"
        ? "Modern A4"
        : "Classic A4";

  return (
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
      <div className="flex flex-col gap-2 border-b border-slate-200 px-3 py-2.5 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex min-w-0 items-center gap-2">
          <Eye className="h-4 w-4 shrink-0 text-cyan-600" />
          <div className="min-w-0">
            <h4 className="text-xs font-semibold text-slate-800">
              Exact print preview
            </h4>
            <p className="truncate text-[9px] text-slate-500">
              Uses the same builders and visible fields as final Quotation
              printing.
            </p>
          </div>
        </div>
        <span className="w-fit rounded-full border border-slate-300 bg-white px-2 py-1 text-[8px] font-bold uppercase tracking-[0.12em] text-slate-600">
          {label}
        </span>
      </div>

      <div className="border-b border-slate-200 bg-slate-50 p-2">
        <div className="grid grid-cols-3 gap-1 rounded-lg border border-slate-200 bg-slate-100 p-1">
          {(
            [
              ["classic", "Classic A4"],
              ["modern", "Modern A4"],
              ["thermal", "80mm Thermal"],
            ] as Array<[QuotationPrintFormat, string]>
          ).map(([value, text]) => (
            <button
              key={value}
              type="button"
              onClick={() => onFormatChange(value)}
              className={`rounded-md px-2 py-1.5 text-[9px] font-semibold transition ${
                format === value
                  ? "bg-white text-slate-900 shadow-sm"
                  : "text-slate-500 hover:bg-white/60 hover:text-slate-800"
              }`}
            >
              {text}
            </button>
          ))}
        </div>
      </div>

      <div className="bg-slate-100 p-3">
        <div
          className={`mx-auto overflow-hidden rounded-xl border border-slate-300 bg-white shadow-lg ${
            format === "thermal" ? "max-w-[310px]" : "w-full max-w-[520px]"
          }`}
        >
          <iframe
            ref={frameRef}
            title={`${label} Quotation template preview`}
            src="about:blank"
            scrolling="no"
            className="block w-full border-0 bg-white"
          />
        </div>
        <p className="mt-2 text-center text-[9px] font-medium text-slate-500">
          Sample values only. Layout and visible fields use the real Quotation
          renderer.
        </p>
      </div>
    </section>
  );
}

export default function QuotationPrintCustomizationPanel({
  format,
  onFormatChange,
}: Props) {
  const [activeTab, setActiveTab] = useState<EditorTab>("style");
  const [prefs, setPrefs] = useState<QuotationPrintCustomization>(
    DEFAULT_QUOTATION_PRINT_CUSTOMIZATION,
  );
  const [colorDraft, setColorDraft] = useState(
    DEFAULT_QUOTATION_PRINT_CUSTOMIZATION.headingColor,
  );
  const [saved, setSaved] = useState(false);

  useEffect(() => {
    const current = getQuotationPrintCustomization();
    setPrefs(current);
    setColorDraft(current.headingColor);

    return subscribeQuotationPrintCustomization((next) => {
      setPrefs(next);
      setColorDraft(next.headingColor);
    });
  }, []);

  function flashSaved() {
    setSaved(true);
    window.setTimeout(() => setSaved(false), 1300);
  }

  function updatePreference<K extends keyof QuotationPrintCustomization>(
    key: K,
    value: QuotationPrintCustomization[K],
  ) {
    const next = setQuotationPrintCustomization({
      [key]: value,
    } as Partial<QuotationPrintCustomization>);
    setPrefs(next);
    if (key === "headingColor") {
      setColorDraft(String(next.headingColor));
    }
    flashSaved();
  }

  function updateToggle(
    key: keyof QuotationPrintCustomization,
    checked: boolean,
  ) {
    const next = setQuotationPrintCustomization({
      [key]: checked,
    } as Partial<QuotationPrintCustomization>);
    setPrefs(next);
    flashSaved();
  }

  function chooseA4Style(style: "classic" | "modern") {
    updatePreference("a4Style", style);
    onFormatChange(style);
  }

  function chooseFormat(next: QuotationPrintFormat) {
    onFormatChange(next);
    if (next !== "thermal") {
      updatePreference("a4Style", next);
    }
  }

  function resetLayout() {
    const next = resetQuotationPrintCustomization();
    setPrefs(next);
    setColorDraft(next.headingColor);
    onFormatChange(next.a4Style === "modern" ? "modern" : "classic");
    flashSaved();
  }

  return (
    <div className="space-y-3">
      <section className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm sm:flex-row sm:items-center sm:justify-between">
        <div className="flex min-w-0 items-center gap-3">
          <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-slate-900 text-cyan-300">
            <LayoutTemplate className="h-4 w-4" />
          </span>
          <div className="min-w-0">
            <h3 className="text-sm font-semibold text-slate-900">
              Quotation template
            </h3>
            <p className="mt-0.5 text-[10px] text-slate-500">
              Changes save automatically and affect Classic, Modern and thermal
              output.
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          {saved ? (
            <span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2 py-1 text-[9px] font-semibold text-emerald-600">
              <Check className="h-3 w-3" />
              Saved
            </span>
          ) : null}
          <button
            type="button"
            onClick={resetLayout}
            className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-2.5 py-1.5 text-[10px] font-semibold text-slate-600 transition hover:border-rose-200 hover:bg-rose-50 hover:text-rose-600"
          >
            <RotateCcw className="h-3 w-3" />
            Reset
          </button>
        </div>
      </section>

      <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        <div className="grid grid-cols-4 border-b border-slate-200 bg-slate-50 p-1">
          {TABS.map((tab) => {
            const Icon = tab.icon;
            const selected = activeTab === tab.key;
            return (
              <button
                key={tab.key}
                type="button"
                onClick={() => setActiveTab(tab.key)}
                className={`inline-flex min-w-0 items-center justify-center gap-1 rounded-lg px-1.5 py-2 text-[9px] font-semibold transition ${
                  selected
                    ? "bg-white text-slate-900 shadow-sm"
                    : "text-slate-500 hover:bg-white/60 hover:text-slate-800"
                }`}
              >
                <Icon className="h-3.5 w-3.5 shrink-0" />
                <span className="truncate">{tab.label}</span>
              </button>
            );
          })}
        </div>

        <div className="p-3">
          {activeTab === "style" ? (
            <div className="space-y-3">
              <div className="flex items-start gap-2.5 rounded-xl border border-slate-200 bg-slate-50 p-3">
                <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-white text-cyan-600 shadow-sm">
                  <Palette className="h-4 w-4" />
                </span>
                <div>
                  <h4 className="text-xs font-semibold text-slate-800">
                    Print appearance
                  </h4>
                  <p className="mt-0.5 text-[9px] leading-4 text-slate-500">
                    Classic and Modern use the same A4 renderer as Sales.
                    Thermal stays monochrome and printer-safe.
                  </p>
                </div>
              </div>

              <div className="grid gap-3 sm:grid-cols-2">
                <div>
                  <label className="mb-1.5 block text-[10px] font-semibold uppercase tracking-[0.1em] text-slate-500">
                    A4 style
                  </label>
                  <div className="grid grid-cols-2 rounded-lg border border-slate-200 bg-slate-100 p-1">
                    {(["classic", "modern"] as const).map((style) => (
                      <button
                        key={style}
                        type="button"
                        onClick={() => chooseA4Style(style)}
                        className={`inline-flex items-center justify-center gap-1.5 rounded-md px-2 py-2 text-[10px] font-semibold capitalize transition ${
                          prefs.a4Style === style
                            ? "bg-white text-slate-900 shadow-sm"
                            : "text-slate-500 hover:text-slate-800"
                        }`}
                      >
                        {prefs.a4Style === style ? (
                          <Check className="h-3 w-3" />
                        ) : null}
                        {style}
                      </button>
                    ))}
                  </div>
                </div>

                <div>
                  <label className="mb-1.5 block text-[10px] font-semibold uppercase tracking-[0.1em] text-slate-500">
                    Heading colour
                  </label>
                  <div className="flex gap-2">
                    <input
                      type="color"
                      value={prefs.headingColor}
                      onChange={(event) =>
                        updatePreference("headingColor", event.target.value)
                      }
                      className="h-9 w-12 cursor-pointer rounded-lg border border-slate-200 bg-white p-1"
                      aria-label="Quotation heading colour"
                    />
                    <input
                      value={colorDraft}
                      onChange={(event) => setColorDraft(event.target.value)}
                      onBlur={() => {
                        const value = colorDraft.trim();
                        if (/^#[0-9a-fA-F]{6}$/.test(value)) {
                          updatePreference("headingColor", value);
                        } else {
                          setColorDraft(prefs.headingColor);
                        }
                      }}
                      onKeyDown={(event) => {
                        if (event.key === "Enter") {
                          event.currentTarget.blur();
                        }
                      }}
                      className={inputClass}
                    />
                  </div>
                </div>
              </div>
            </div>
          ) : null}

          {activeTab === "business" ? (
            <ToggleGrid
              definitions={BUSINESS_TOGGLES}
              prefs={prefs}
              onChange={updateToggle}
            />
          ) : null}

          {activeTab === "quotation" ? (
            <ToggleGrid
              definitions={QUOTATION_TOGGLES}
              prefs={prefs}
              onChange={updateToggle}
            />
          ) : null}

          {activeTab === "items" ? (
            <ToggleGrid
              definitions={ITEM_TOGGLES}
              prefs={prefs}
              onChange={updateToggle}
            />
          ) : null}
        </div>
      </section>

      <QuotationTemplatePreview
        prefs={prefs}
        format={format}
        onFormatChange={chooseFormat}
      />
    </div>
  );
}
