"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import {
  Building2,
  Check,
  FileText,
  LayoutTemplate,
  PackageSearch,
  Palette,
  RotateCcw,
} from "lucide-react";
import {
  DEFAULT_SALES_PRINT_CUSTOMIZATION,
  getSalesPrintCustomization,
  resetSalesPrintCustomization,
  setSalesPrintCustomization,
  subscribeSalesPrintCustomization,
  type SalesPrintCustomization,
} from "@/lib/print/salesPrintCustomization";
import { buildInvoiceHtml } from "@/lib/print/buildInvoiceHtml";

type ToggleDefinition = {
  key: keyof SalesPrintCustomization;
  label: string;
  description: string;
};

type EditorTab = "style" | "business" | "sale" | "items";

const BUSINESS_TOGGLES: ToggleDefinition[] = [
  {
    key: "showLogo",
    label: "Logo",
    description: "Show the saved business logo.",
  },
  {
    key: "showShopName",
    label: "Business name",
    description: "Show the shop or company name.",
  },
  {
    key: "showShopAddress",
    label: "Address",
    description: "Show the saved business address.",
  },
  {
    key: "showShopPhone",
    label: "Phone",
    description: "Show the business phone.",
  },
  {
    key: "showShopEmail",
    label: "Email",
    description: "Show the business email.",
  },
  {
    key: "showShopGstin",
    label: "GSTIN",
    description: "Show the business GST number.",
  },
];

const SALE_TOGGLES: ToggleDefinition[] = [
  {
    key: "showCustomerName",
    label: "Customer name",
    description: "Show customer or cash-customer identity.",
  },
  {
    key: "showCustomerAddress",
    label: "Customer address",
    description: "Show the customer address when available.",
  },
  {
    key: "showCustomerPhone",
    label: "Customer phone",
    description: "Show the customer phone when available.",
  },
  {
    key: "showCustomerGstin",
    label: "Customer GSTIN",
    description: "Show the customer GSTIN when available.",
  },
  {
    key: "showEntryNo",
    label: "Entry number",
    description: "Show the internal Sales entry number.",
  },
  {
    key: "showBillNo",
    label: "Bill number",
    description: "Show the generated Sales bill number.",
  },
  {
    key: "showSaleDate",
    label: "Sale date",
    description: "Show the saved Sales date.",
  },
  {
    key: "showEntryTime",
    label: "Entry time",
    description: "Show the saved entry time.",
  },
  {
    key: "showSaleType",
    label: "Sale type",
    description: "Show Cash or Credit.",
  },
  {
    key: "showTransactionType",
    label: "Transaction type",
    description: "Show the selected transaction type.",
  },
  {
    key: "showDepartment",
    label: "Department",
    description: "Show the optional department.",
  },
  {
    key: "showDebitAccount",
    label: "Debit account",
    description: "Show the optional debit account.",
  },
  {
    key: "showNatureOfEntry",
    label: "Nature of entry",
    description: "Show the optional Sales description.",
  },
];

const ITEM_TOGGLES: ToggleDefinition[] = [
  {
    key: "showBarcode",
    label: "Barcode",
    description: "Show barcode below each item.",
  },
  {
    key: "showBatchNo",
    label: "Batch number",
    description: "Show batch information when available.",
  },
  {
    key: "showExpiryDate",
    label: "Expiry",
    description: "Show item expiry information.",
  },
  { key: "showUnit", label: "Unit", description: "Show unit with quantity." },
  {
    key: "showTax",
    label: "Tax",
    description: "Show included tax value and percentage.",
  },
  {
    key: "showMrp",
    label: "MRP",
    description: "Show the MRP column on A4 and item detail on thermal.",
  },
  {
    key: "showOffers",
    label: "Offers",
    description: "Show applied offers and savings.",
  },
  {
    key: "showSubTotal",
    label: "Subtotal",
    description: "Show the subtotal line.",
  },
  {
    key: "showBillDiscount",
    label: "Bill discount",
    description: "Show bill-level discount.",
  },
  {
    key: "showOfferSavings",
    label: "Offer savings",
    description: "Show total offer savings.",
  },
  {
    key: "showAmountInWords",
    label: "Amount in words",
    description: "Write the final amount in words.",
  },
  {
    key: "showTerms",
    label: "Terms / footer note",
    description: "Show the Business Profile footer note.",
  },
  {
    key: "showAuthorizedSignatory",
    label: "Authorized signature",
    description: "Show the signature area.",
  },
  {
    key: "showKynflowFooter",
    label: "KYNFLOW footer",
    description: "Show the Generated by KYNFLOW line.",
  },
];

const tabs: Array<{
  key: EditorTab;
  label: string;
  description: string;
  icon: typeof Palette;
}> = [
  { key: "style", label: "Style", description: "A4 appearance", icon: Palette },
  {
    key: "business",
    label: "Business",
    description: "Header visibility",
    icon: Building2,
  },
  {
    key: "sale",
    label: "Sales",
    description: "Customer and bill fields",
    icon: FileText,
  },
  {
    key: "items",
    label: "Items & Footer",
    description: "Rows and totals",
    icon: PackageSearch,
  },
];

const inputClass =
  "w-full rounded-lg border border-slate-200 bg-white px-2.5 py-2 text-xs text-slate-800 outline-none transition placeholder:text-slate-400 focus:border-cyan-400 focus:ring-2 focus:ring-cyan-100";

function ToggleRow({
  definition,
  checked,
  onChange,
}: {
  definition: ToggleDefinition;
  checked: boolean;
  onChange: (checked: boolean) => void;
}) {
  return (
    <button
      type="button"
      onClick={() => onChange(!checked)}
      className={`flex min-h-[50px] items-center justify-between gap-3 rounded-xl border px-3 py-2 text-left transition ${
        checked
          ? "border-slate-300 bg-white shadow-sm"
          : "border-slate-200 bg-slate-100/70"
      } hover:border-cyan-300`}
      aria-pressed={checked}
    >
      <span className="min-w-0">
        <span className="block text-[11px] font-semibold text-slate-800">
          {definition.label}
        </span>
        <span className="mt-0.5 block text-[9px] leading-[14px] text-slate-500">
          {definition.description}
        </span>
      </span>
      <span
        className={`relative inline-flex h-5 w-9 shrink-0 items-center rounded-full transition ${
          checked ? "bg-cyan-500" : "bg-slate-300"
        }`}
      >
        <span
          className={`h-3.5 w-3.5 rounded-full bg-white shadow transition-transform ${
            checked ? "translate-x-[18px]" : "translate-x-[3px]"
          }`}
        />
      </span>
    </button>
  );
}

function ToggleGrid({
  definitions,
  prefs,
  onChange,
}: {
  definitions: ToggleDefinition[];
  prefs: SalesPrintCustomization;
  onChange: (key: keyof SalesPrintCustomization, checked: boolean) => void;
}) {
  return (
    <div className="grid gap-2 sm:grid-cols-2">
      {definitions.map((definition) => (
        <ToggleRow
          key={String(definition.key)}
          definition={definition}
          checked={Boolean(prefs[definition.key])}
          onChange={(checked) => onChange(definition.key, checked)}
        />
      ))}
    </div>
  );
}

function SalesTemplatePreview({ prefs }: { prefs: SalesPrintCustomization }) {
  const previewHtml = useMemo(() => {
    const html = buildInvoiceHtml({
      shop: {
        name: "KYNSTACK TRADERS",
        logoUrl: null,
        addressLine1: "Business Street",
        addressLine2: "Market Junction",
        city: "Kochi",
        state: "Kerala",
        pincode: "682001",
        mobile: "+91 98765 43210",
        email: "billing@example.com",
        gstin: "32ABCDE1234F1Z5",
        footerNote: "Thank you for your business.",
        authorizedSignatory: "Authorized Signatory",
      },
      options: prefs,
      document: {
        title: prefs.documentTitle,
        entryNo: "SE-000128",
        billNo: "INV-2841",
        date: "2026-08-06",
        time: "2026-08-06T14:30:00",
        saleType: "Cash",
        typeLabel: "Retail Sale",
        department: "Main Store",
        debitAccount: "Cash Account",
        natureOfEntry: "Counter sale",
      },
      party: {
        label: "Customer",
        name: "Sample Customer",
        address: "Market Road, Kochi, Kerala - 682018",
        mobile: "+91 98470 12345",
        gstin: "32ABCDE1234F1Z5",
      },
      items: [
        {
          lineNo: 1,
          name: "Premium Product",
          barcode: "8901234567890",
          batchNo: "B-2408",
          expiryDate: "2027-08-31",
          qty: 2,
          unit: "NOS",
          rate: 1250,
          taxPercent: "P18",
          mrp: 1499,
          offerName: "Festival Offer",
          offerDiscountAmount: 100,
          amount: 2400,
        },
        {
          lineNo: 2,
          name: "Standard Product",
          barcode: "8901234567000",
          batchNo: "B-2409",
          qty: 1,
          unit: "NOS",
          rate: 650,
          taxPercent: "P5",
          mrp: 699,
          amount: 650,
        },
      ],
      subTotal: 3050,
      discount: 50,
      offerSavings: 100,
      offerSummary: ["Festival Offer: Premium Product"],
      grandTotal: 3000,
    });

    const fitStyles = [
      '<style id="kynflow-sales-template-preview-fit">',
      "html, body { width: 210mm !important; min-height: 297mm !important; margin: 0 !important; overflow: hidden !important; background: #ffffff !important; }",
      "body { transform-origin: top left !important; }",
      ".invoice { margin: 0 auto !important; box-shadow: none !important; }",
      "</style>",
    ].join("");

    return html.replace("</head>", `${fitStyles}</head>`);
  }, [prefs]);

  const previewFrameRef = useRef<HTMLIFrameElement>(null);

  useEffect(() => {
    const frame = previewFrameRef.current;
    if (!frame) return;

    const doc = frame.contentDocument;
    if (!doc) return;

    let cancelled = false;
    let animationFrame = 0;
    let retryTimer = 0;
    let resizeObserver: ResizeObserver | null = null;

    const fitPage = () => {
      if (cancelled || !doc.body || !doc.documentElement) return;

      const viewportWidth = frame.clientWidth;
      if (viewportWidth <= 0) return;

      const pageWidthPx = (210 * 96) / 25.4;
      const pageHeightPx = (297 * 96) / 25.4;
      const scale = Math.min(1, viewportWidth / pageWidthPx);

      doc.documentElement.style.width = `${pageWidthPx}px`;
      doc.documentElement.style.height = `${pageHeightPx}px`;
      doc.documentElement.style.overflow = "hidden";
      doc.body.style.width = `${pageWidthPx}px`;
      doc.body.style.minHeight = `${pageHeightPx}px`;
      doc.body.style.transformOrigin = "top left";
      doc.body.style.transform = `scale(${scale})`;
      doc.body.style.overflow = "hidden";
    };

    doc.open();
    doc.write(previewHtml);
    doc.close();

    animationFrame = window.requestAnimationFrame(fitPage);
    retryTimer = window.setTimeout(fitPage, 180);

    if (typeof ResizeObserver !== "undefined") {
      resizeObserver = new ResizeObserver(fitPage);
      resizeObserver.observe(frame);
    }

    window.addEventListener("resize", fitPage);

    return () => {
      cancelled = true;
      window.cancelAnimationFrame(animationFrame);
      window.clearTimeout(retryTimer);
      resizeObserver?.disconnect();
      window.removeEventListener("resize", fitPage);
    };
  }, [previewHtml]);

  const isModern = prefs.a4Style === "modern";

  return (
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
      <div className="flex items-center justify-between gap-3 border-b border-slate-200 px-3 py-2.5">
        <div className="min-w-0">
          <h4 className="text-xs font-semibold text-slate-800">
            Exact A4 preview
          </h4>
          <p className="truncate text-[9px] text-slate-500">
            Uses the same renderer and visible fields as the final Sales bill.
          </p>
        </div>
        <span className="rounded-full border border-slate-300 bg-white px-2 py-1 text-[8px] font-bold uppercase tracking-[0.12em] text-slate-600">
          {isModern ? "Modern A4" : "Classic A4"}
        </span>
      </div>

      <div className="bg-slate-100 p-3 sm:p-4">
        <div className="mx-auto w-full max-w-[560px] overflow-hidden rounded-xl border border-slate-300 bg-white shadow-lg">
          <iframe
            ref={previewFrameRef}
            title={`${isModern ? "Modern" : "Classic"} Sales template preview`}
            src="about:blank"
            scrolling="no"
            className="block aspect-[210/297] w-full border-0 bg-white"
          />
        </div>

        <p className="mt-2 text-center text-[9px] font-medium text-slate-500">
          The complete A4 page is scaled to fit this preview without clipping.
        </p>
      </div>
    </section>
  );
}

export default function SalesPrintCustomizationPanel() {
  const [activeTab, setActiveTab] = useState<EditorTab>("style");
  const [prefs, setPrefs] = useState<SalesPrintCustomization>(
    DEFAULT_SALES_PRINT_CUSTOMIZATION,
  );
  const [colorDraft, setColorDraft] = useState(
    DEFAULT_SALES_PRINT_CUSTOMIZATION.headingColor,
  );
  const [saved, setSaved] = useState(false);

  useEffect(() => {
    const current = getSalesPrintCustomization();
    setPrefs(current);
    setColorDraft(current.headingColor);
    return subscribeSalesPrintCustomization((next) => {
      setPrefs(next);
      setColorDraft(next.headingColor);
    });
  }, []);

  function flashSaved() {
    setSaved(true);
    window.setTimeout(() => setSaved(false), 1300);
  }

  function updatePreference(
    key: keyof SalesPrintCustomization,
    value: string | boolean,
  ) {
    const next = setSalesPrintCustomization({
      [key]: value,
    } as Partial<SalesPrintCustomization>);
    setPrefs(next);
    flashSaved();
  }

  function resetLayout() {
    const next = resetSalesPrintCustomization();
    setPrefs(next);
    setColorDraft(next.headingColor);
    flashSaved();
  }

  return (
    <div className="space-y-3">
      <section className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm sm:flex-row sm:items-center sm:justify-between">
        <div className="flex min-w-0 items-center gap-3">
          <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-slate-900 text-emerald-300">
            <LayoutTemplate className="h-4 w-4" />
          </span>
          <div className="min-w-0">
            <h3 className="text-sm font-semibold text-slate-900">
              Sales bill template
            </h3>
            <p className="mt-0.5 text-[10px] text-slate-500">
              Changes save automatically and affect A4 and thermal output.
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          {saved && (
            <span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-2 py-1 text-[9px] font-semibold text-emerald-600">
              <Check className="h-3 w-3" />
              Saved
            </span>
          )}
          <button
            type="button"
            onClick={resetLayout}
            className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-2.5 py-1.5 text-[10px] font-semibold text-slate-600 transition hover:border-rose-200 hover:bg-rose-50 hover:text-rose-600"
          >
            <RotateCcw className="h-3 w-3" />
            Reset
          </button>
        </div>
      </section>

      <div className="grid grid-cols-2 gap-1 rounded-xl border border-slate-200 bg-slate-100 p-1 sm:grid-cols-4">
        {tabs.map((tab) => {
          const Icon = tab.icon;
          const active = activeTab === tab.key;
          return (
            <button
              key={tab.key}
              type="button"
              onClick={() => setActiveTab(tab.key)}
              className={`flex min-w-0 items-center gap-2 rounded-lg px-2.5 py-2 text-left transition ${
                active
                  ? "bg-white text-slate-900 shadow-sm"
                  : "text-slate-500 hover:bg-white/60 hover:text-slate-800"
              }`}
            >
              <Icon
                className={`h-3.5 w-3.5 shrink-0 ${
                  active ? "text-emerald-600" : "text-slate-400"
                }`}
              />
              <span className="min-w-0">
                <span className="block truncate text-[10px] font-semibold">
                  {tab.label}
                </span>
                <span className="hidden truncate text-[8px] text-slate-400 sm:block">
                  {tab.description}
                </span>
              </span>
            </button>
          );
        })}
      </div>

      {activeTab === "style" && (
        <section className="rounded-2xl border border-slate-200 bg-white p-3 shadow-sm">
          <div className="mb-3 flex items-center gap-2">
            <Palette className="h-4 w-4 text-emerald-600" />
            <div>
              <h4 className="text-xs font-semibold text-slate-800">
                A4 design
              </h4>
              <p className="text-[9px] text-slate-500">
                Thermal remains monochrome and printer-safe.
              </p>
            </div>
          </div>
          <div className="grid gap-3 sm:grid-cols-2">
            <div>
              <label className="mb-1.5 block text-[10px] font-semibold uppercase tracking-[0.1em] text-slate-500">
                A4 style
              </label>
              <div className="grid grid-cols-2 rounded-xl border border-slate-200 bg-slate-100 p-1">
                {(["classic", "modern"] as const).map((style) => (
                  <button
                    key={style}
                    type="button"
                    onClick={() => updatePreference("a4Style", style)}
                    className={`rounded-lg px-3 py-2 text-xs font-semibold capitalize transition ${
                      prefs.a4Style === style
                        ? "bg-white text-slate-900 shadow-sm"
                        : "text-slate-500 hover:text-slate-800"
                    }`}
                  >
                    {style}
                  </button>
                ))}
              </div>
            </div>
            <div>
              <label className="mb-1.5 block text-[10px] font-semibold uppercase tracking-[0.1em] text-slate-500">
                Heading colour
              </label>
              <div className="flex gap-2">
                <input
                  type="color"
                  value={prefs.headingColor}
                  onChange={(event) =>
                    updatePreference("headingColor", event.target.value)
                  }
                  className="h-9 w-12 rounded-lg border border-slate-200 bg-white p-1"
                />
                <input
                  value={colorDraft}
                  onChange={(event) => setColorDraft(event.target.value)}
                  onBlur={() => updatePreference("headingColor", colorDraft)}
                  onKeyDown={(event) => {
                    if (event.key === "Enter") {
                      updatePreference("headingColor", colorDraft);
                    }
                  }}
                  className={inputClass}
                />
              </div>
            </div>
            <div className="sm:col-span-2">
              <label className="mb-1.5 block text-[10px] font-semibold uppercase tracking-[0.1em] text-slate-500">
                Document title
              </label>
              <input
                value={prefs.documentTitle}
                onChange={(event) =>
                  updatePreference("documentTitle", event.target.value)
                }
                placeholder="Sales Invoice"
                className={inputClass}
              />
            </div>
          </div>
        </section>
      )}

      {activeTab === "business" && (
        <ToggleGrid
          definitions={BUSINESS_TOGGLES}
          prefs={prefs}
          onChange={updatePreference}
        />
      )}
      {activeTab === "sale" && (
        <ToggleGrid
          definitions={SALE_TOGGLES}
          prefs={prefs}
          onChange={updatePreference}
        />
      )}
      {activeTab === "items" && (
        <ToggleGrid
          definitions={ITEM_TOGGLES}
          prefs={prefs}
          onChange={updatePreference}
        />
      )}

      <SalesTemplatePreview prefs={prefs} />
    </div>
  );
}
